### ISSUE TITLE
`FAME.workdb()` fails in folder with spaces

### ISSUE THREAD

**Issue by Nic2020** [bankofcanada/FAME.jl#12]
The test below fails if the folder has a space in it (at least on Linux).
```
FAME.init_chli()
input_options = Workspace(a = "abc", b= 2)
FAME.workdb() do wk
   writefame(wk,input_options)
end
```
<img width="659" alt="2023-06-20_09-07-06" src="https://github.com/bankofcanada/FAME.jl/assets/30166151/992612e0-423c-4912-98b8-91eb2eb84c6a">

**Comment by bbejanov** [comment]
This seems to be a bug in FAME itself.  According to CHLI documentation, HBMODE (5) is not even one of the status codes that `cfmopwk` can return!?  I'm not sure we can fix this from Julia

**Comment by bbejanov** [comment]
Environment variable `FAME_TEMP` controls the location where CHLI will store the workdb temporary files. If not set, then CHLI uses the current directory. Setting it to a path without spaces seems to work around this problem.

![image](https://github.com/bankofcanada/FAME.jl/assets/12414774/d1ecc32f-90c9-40c5-bdb2-a5f49db3fbee)

**Comment by Nic2020** [comment]
Thank you @bbejanov . By re-directing FAME temporary folder to a path without a space, I was able to go around this limitation.

**Comment by Nic2020** [comment]
A work around was provided.
